### ISSUE TITLE
TODO Maschinenbau

### ISSUE THREAD

**Issue by adyvs** [accefa/pren2#79]
- [x] Fixierung für Ballnachschieber
- [x] Neue Halter Gegendruckplatte
- [x] Reibung verringern zwischen den Drehtellern
- [x] Komponentenliste updaten (Advys)
- [ ] Schraubensicherungen 
- [ ] Seitenhalterungen befestigen (Ein Langloch, Eine Bohrung + Bohrungen in Seitenwand) (Advys)
- [x] Hutmuttern bei BLDC Motor (Advys)
- [ ] Band bei Drehrad erneuern 
- [x] Obere Stangenbefestigung (Sc)
- [x] Montage des Gegendruckdings (Sc)
- [x] Montage Ballnachschub (Sp)
- [x] Montage Sensoren + Elektronik-Komponenten (Advys)
- [x] Kleben komplette Maschine
- [x] Ästhetische Anpassungen
- [ ] Zweikomponentenkleber Alu-Führungen

**Comment by alexsuter** [comment]
Milestone?
